server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # create가 되어있는지 확인해야함. 왜냐하면 이것을 수정해서 update, none.. 할수있음.
                       # create는 프로젝트를 재실행 할 때 마다 새로 생성하겠다는 의미임.
                       # 프로젝트 완성 후 update로 변경해야 함.
      naming:
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Entity(테이블)을 만들 때 변수명 그대로 데이터베이스 필드에 넣어준다는 의미.
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # Entity(테이블)을 만들 때 카멜 표기법을 언더바 표기법으로 바꿔서 넣음.
      use-new-id-generator-mappings: false # 넘버링 방식, false는 jpa가 사용하는 기본 넘버링을 따라가지 않는다.
#    show-sql: true
    properties:
      hibernate.format_sql: true
      globally_quoted_identifiers: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql


  jackson:
    serialization:
      fail-on-empty-beans: false

  devtools:
    livereload:
      enabled: true
